### ISSUE TITLE
Generate vital sign with normal dist.

### ISSUE THREAD

**Issue by rdinizcal** [leooleo/bsn#2]
Ator: Nó Sensor

Objetivo pai: "Coletar sinais vitais"

Descrição: "Implementar procedimento para gerar sinais vitais a partir de distribuição normal."

![image](https://user-images.githubusercontent.com/18559295/41064176-21fbd60c-69b1-11e8-9ff8-48de9f7548ec.png)

**Comment by gabrielevi10** [comment]
Done!

**Comment by rdinizcal** [comment]
A implementação da geração de sinais vital por normal ficou boa! Porém não entedi o handler.. ele foi implementado somente para teste? E os testes unitários, cadê?

**Comment by gabrielevi10** [comment]
O handler não necessariamente é somente para teste, pois a base para continuar o desenvolvimento já está lá. No caso, por enquanto, apenas mostra se recebeu o sinal gerado de forma correta. Ainda não desenvolvi os testes.
